local keyOrder = {
    "message",
    "parseESPs",
    "skillCap",
    "skillNames",
    "fMajorSkillBonus",
    "fMinorSkillBonus",
    "fMiscSkillBonus",
    "fSpecialSkillBonus",
    "iLevelUpTotal",
    "iLevelUpMajorMult",
    "iLevelUpMinorMult",
    "iLevelUpMajorMultAttribute",
    "iLevelUpMinorMultAttribute",
    "iLevelupMiscMultAttriubte",
}

local values = {
    message = {
        enabled = true,
        text = "Your %s skill increased to %s",
        sound = "fx/inter/levelUP.wav",
        id = 6666,
    },
    parseESPs = false,
    skillCap = 100,
    skillNames = {
        ["Block"] = "Block",
        ["Alchemy"] = "Alchemy",
        ["Restoration"] = "Restoration",
        ["Conjuration"] = "Conjuration",
        ["Marksman"] = "Marksman",
        ["Mediumarmor"] = "Medium Armor",
        ["Alteration"] = "Alteration",
        ["Heavyarmor"] = "Heavy Armor",
        ["Mercantile"] = "Mercantile",
        ["Shortblade"] = "Short Blade",
        ["Acrobatics"] = "Acrobatics",
        ["Sneak"] = "Sneak",
        ["Lightarmor"] = "Light Armor",
        ["Longblade"] = "Long Blade",
        ["Armorer"] = "Armorer",
        ["Speechcraft"] = "Speechcraft",
        ["Axe"] = "Axe",
        ["Security"] = "Security",
        ["Enchant"] = "Enchant",
        ["Destruction"] = "Destruction",
        ["Athletics"] = "Athletics",
        ["Illusion"] = "Illusion",
        ["Mysticism"] = "Mysticism",
        ["Spear"] = "Spear",
        ["Bluntweapon"] = "Blunt Weapon",
        ["Handtohand"] = "Hand-to-hand",
        ["Unarmored"] = "Unarmored",
    },
    fMajorSkillBonus = 0.75,
    fMinorSkillBonus = 1,
    fMiscSkillBonus = 1.25,
    fSpecialSkillBonus = 0.8,
    iLevelUpTotal = 10,
    iLevelUpMajorMult = 1,
    iLevelUpMinorMult = 1,
    iLevelUpMajorMultAttribute = 1,
    iLevelUpMinorMultAttribute = 1,
    iLevelupMiscMultAttriubte = 1,
}

return { keyOrder = keyOrder, values = values }